version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      # @electron-forge/plugin-fuses@7.11.1 requires @electron/fuses version 1.x.
      - dependency-name: "@electron/fuses"
        versions:
          - "> 1.8.0"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: quarterly
